### PR TITLE
The form-control class on a checkbox creates strange artifacts

### PR DESCRIPTION
**Pull request by atesgoral**

### CODE REVIEW

**Comment by titaniumbones** [comment]
do you mean the weird flashing of the checkbox? Would be nice to fix that!

Can't figure out an efficient way to submit a pr to you but here's a patch:

``` patch
attributes.patch
From a8470af42ff56ee73ca2d34fce86e3eec74508e7 Mon Sep 17 00:00:00 2001
From: Matt Price <matt.price@utoronto.ca>
Date: Tue, 17 Jan 2017 19:14:33 -0500
Subject: [PATCH 7/7] added new class to preserve some checkbox attributes

with no css, the checkbox ends up very tiny and offset.
---
 popup.html | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/popup.html b/popup.html
index 94dbfc8..9d14cd4 100644
--- a/popup.html
+++ b/popup.html
@@ -8,6 +8,7 @@ div.quick-col {max-width: 48%; padding-right:2%; float:left;}
 div.clear{clear:both;}
 .form-group {margin-bottom: 10px;}
 .agency-code input, #subprimerID { width: 70px; display: inline-block; }
+.form-checkbox {width:100%; height: 25px;}
 html, body {min-height: 600px;}
 </style>
 <div id="nominationTool">
@@ -615,7 +616,7 @@ html, body {min-height: 600px;}
             Uncrawlable content?
           </label>
           <br>
-          <input type="checkbox" id="crawlableID" name="crawlableID" value="Yes"/>
+          <input type="checkbox" id="crawlableID" name="crawlableID" class="form-checkbox" value="Yes"/>
         </div>
         <div class="clear"></div>
         <h3 id="success"></h3>
-- 
```

**Comment by atesgoral** [comment]
I hadn't noticed a weird flashing effect. Could it be the weird box around the checkbox that gets highlighted when you click the checkbox? If that's the one, this change fixes it by removing the wrongly used form field class.

I didn't see any mentions of the `form-checkbox` class in the Bootstrap documentation. What is it supposed to do?

**Comment by atesgoral** [comment]
@titaniumbones bump

**Comment by titaniumbones** [comment]
sorry to miss this.  long week!

**Pull request merged**
