### PR TITLE
Add options list for agencies + manual event entry for localstorage

### PR DESCRIPTION
**Pull request by mi-lee**
- Now you have an options list for agency to choose, and localstorage should populate it once selected the first time
- event name can be manually entered instead of hardcoded.

@titaniumbones r?

### CODE REVIEW

**Comment by titaniumbones** [comment]
I uncommented the eventname field in the popup form. Looks great! Thank you. @sonalranjit does it look good to you?

**Review by titaniumbones — APPROVED** [review]
looks great.

**Review by sonalranjit — APPROVED** [review]
Looks good just tested it out

**Comment by mi-lee** [comment]
I'll merge although not sure how to republish to the chrome extension store.

**Pull request merged**
