### PR TITLE
Cut down option markup by 50% by dropping values

### PR DESCRIPTION
**Pull request by atesgoral**

### CODE REVIEW

**Comment by sonalranjit** [comment]
These changes were giving me error when i tried to submit on this [url](https://github.com/edgi-govdata-archiving/presidential-harvest-nomination-tool/pull/32/commits/21906a940ce7e3c422df213c8277f026a8bf882c) @atesgoral would you mind checking it out? other commits are succesfully working and submitting.

**Comment by atesgoral** [comment]
@sonalranjit I'll retest. Did you happen to capture what the error you were getting was?

**Comment by atesgoral** [comment]
It seems like the data is submitted fine, but the popup ends up showing an error. Investigating.

**Comment by atesgoral** [comment]
@sonalranjit I've tested it locally and everything seems fine. I was initially getting an error, but that was due to a CORS failure while testing the popup off a local server.

**Comment by mi-lee** [comment]
Same as Sonal - got a 400 with this github link (i.e. this repo) but it's fine for other links. @titaniumbones I think it should be fine to merge.

**Comment by atesgoral** [comment]
So, you were getting a 400 Bad Request response from GitHub?

**Comment by mi-lee** [comment]
From Google Forms.

**Comment by atesgoral** [comment]
@mi-lee Can you tell me the exact values you're using in the tool?

**Comment by atesgoral** [comment]
@sonalranjit Are you able to reproduce the issue you saw? What exact values did you use? I see no reason for this markup simplification + proper use of jQuery's `.val()` to change the behaviour.

**Comment by titaniumbones** [comment]
hey are we good to merge this, sorry to have been so far behind on this...

**Comment by atesgoral** [comment]
@mi-lee, @sonalranjit *bump*

**Pull request merged**
