### PR TITLE
Remove uncrawlable

### PR DESCRIPTION
**Pull request by sonalranjit**
Applied changes requested in #38

### CODE REVIEW

**Comment by titaniumbones** [comment]
@ambergman @trinberg can you guys confirm that this is what you want, maybe by downloading the branch and testing the ui?

(Am already in bed w computer closed, so don't do it myself tonight)

**Review by atesgoral — APPROVED** [review]

**Comment by titaniumbones** [comment]
Won't not don't.

**Comment by titaniumbones** [comment]
from @trinberg : 
```
REPLACE "Visualization" text with "Visualization/Interactive"
REPLACE "Complex/Hard" text with "Many Files"
ADD checkbox field with a header "Database"
@ambergman and I think the comment field is useful, but the added cost is that it makes the extension too big and produces the scrollbar. For now, I'd suggest:

REMOVE "comment" header and comment input box
Regarding formatting: If possible, keep the chrome extension as small in height as possible - the scrollbar can be difficult on certain machines/browsers.
```

**Comment by titaniumbones** [comment]
I added the additional field they wanted, made some CSS changes to permit the Comment field to show up without scrolling.  Looks like everything works, so I'm going to commit, though @sonalranjit @trinberg may want to follow up to make sure it's all good.

**Comment by sonalranjit** [comment]
@titaniumbones just reviewed your push, looks great ready to merge. Thanks for expanding the width and the css. Whoever is merging this please rebase and merge. Also once this is merged we need to update the master branch with this version. I requested the pull request to be onto harvard-edgi because that was the most recent/updated branch.

**Comment by titaniumbones** [comment]
by rebase do you mean squash or something more complicated? if just
squashing I'll do it now.

**Comment by sonalranjit** [comment]
screen shot 2017-02-01 at 8 29 36 am
 Just the third option from the dropdown. @titaniumbones

**Comment by titaniumbones** [comment]
oh sweet, I'll rebase both branches.

**Comment by titaniumbones** [comment]
add new fields to popup

**Pull request merged**
